//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konvolucio.MCAN120803.GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public double splitContainerMainView_SplitterDistance {
            get {
                return ((double)(this["splitContainerMainView_SplitterDistance"]));
            }
            set {
                this["splitContainerMainView_SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double splitContainerMainTree_SplitterDistance {
            get {
                return ((double)(this["splitContainerMainTree_SplitterDistance"]));
            }
            set {
                this["splitContainerMainTree_SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nincs")]
        public string TextData {
            get {
                return ((string)(this["TextData"]));
            }
            set {
                this["TextData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TraceViewAutoScroll {
            get {
                return ((bool)(this["TraceViewAutoScroll"]));
            }
            set {
                this["TraceViewAutoScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableSingleInstance {
            get {
                return ((bool)(this["EnableSingleInstance"]));
            }
            set {
                this["EnableSingleInstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MainFormWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MainFormWindowState"]));
            }
            set {
                this["MainFormWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("851, 459")]
        public global::System.Drawing.Size MainFormSize {
            get {
                return ((global::System.Drawing.Size)(this["MainFormSize"]));
            }
            set {
                this["MainFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDeveloperMode {
            get {
                return ((bool)(this["IsDeveloperMode"]));
            }
            set {
                this["IsDeveloperMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string CurrentCultureName {
            get {
                return ((string)(this["CurrentCultureName"]));
            }
            set {
                this["CurrentCultureName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Set By First Start")]
        public string BrowseLocation {
            get {
                return ((string)(this["BrowseLocation"]));
            }
            set {
                this["BrowseLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFirstStart {
            get {
                return ((bool)(this["IsFirstStart"]));
            }
            set {
                this["IsFirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowWorkingDirectoryInTitleBar {
            get {
                return ((bool)(this["ShowWorkingDirectoryInTitleBar"]));
            }
            set {
                this["ShowWorkingDirectoryInTitleBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SenderPanelHide {
            get {
                return ((bool)(this["SenderPanelHide"]));
            }
            set {
                this["SenderPanelHide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadProjectOnAppllicationStart {
            get {
                return ((bool)(this["LoadProjectOnAppllicationStart"]));
            }
            set {
                this["LoadProjectOnAppllicationStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.23")]
        public double splitContainerLog_SplitterDistance {
            get {
                return ((double)(this["splitContainerLog_SplitterDistance"]));
            }
            set {
                this["splitContainerLog_SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double splitContainerStatistics_SplitterDistance {
            get {
                return ((double)(this["splitContainerStatistics_SplitterDistance"]));
            }
            set {
                this["splitContainerStatistics_SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double splitContainerLogDesciription_SplitterDistance {
            get {
                return ((double)(this["splitContainerLogDesciription_SplitterDistance"]));
            }
            set {
                this["splitContainerLogDesciription_SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ApplictionSettingsUpgradeCounter {
            get {
                return ((int)(this["ApplictionSettingsUpgradeCounter"]));
            }
            set {
                this["ApplictionSettingsUpgradeCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ApplictionSettingsSaveCounter {
            get {
                return ((int)(this["ApplictionSettingsSaveCounter"]));
            }
            set {
                this["ApplictionSettingsSaveCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double splitContainerTraceSender_SplitterDistance {
            get {
                return ((double)(this["splitContainerTraceSender_SplitterDistance"]));
            }
            set {
                this["splitContainerTraceSender_SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KeyTracingEnable {
            get {
                return ((bool)(this["KeyTracingEnable"]));
            }
            set {
                this["KeyTracingEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int GuiRefreshRateMs {
            get {
                return ((int)(this["GuiRefreshRateMs"]));
            }
            set {
                this["GuiRefreshRateMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int dataGridViewTraceRefreshRateMs {
            get {
                return ((int)(this["dataGridViewTraceRefreshRateMs"]));
            }
            set {
                this["dataGridViewTraceRefreshRateMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Threading.ThreadPriority SenderThreadPriority {
            get {
                return ((global::System.Threading.ThreadPriority)(this["SenderThreadPriority"]));
            }
            set {
                this["SenderThreadPriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Threading.ThreadPriority AdapterThreadPriority {
            get {
                return ((global::System.Threading.ThreadPriority)(this["AdapterThreadPriority"]));
            }
            set {
                this["AdapterThreadPriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SenderThreadSleepMs {
            get {
                return ((int)(this["SenderThreadSleepMs"]));
            }
            set {
                this["SenderThreadSleepMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int dataGridViewStatisticsRefreshRateMs {
            get {
                return ((int)(this["dataGridViewStatisticsRefreshRateMs"]));
            }
            set {
                this["dataGridViewStatisticsRefreshRateMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppTraceScroll {
            get {
                return ((bool)(this["AppTraceScroll"]));
            }
            set {
                this["AppTraceScroll"] = value;
            }
        }
    }
}
